_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  components: 0
  config: 0
  config_direct_save: 0
  config_filter: 0
  config_ignore: 0
  config_split: 0
  contextual: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  emulsify_twig: 0
  facets: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  fk_glossary_block: 0
  fk_karaoke_custom: 0
  help: 0
  history: 0
  image: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  link: 0
  login_emailusername: 0
  menu_ui: 0
  metatag: 0
  metatag_dc: 0
  metatag_dc_advanced: 0
  metatag_mobile: 0
  metatag_open_graph: 0
  mysql: 0
  node: 0
  openid_connect: 0
  openkj: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quickedit: 0
  r4032login: 0
  rdf: 0
  rest: 0
  restui: 0
  search_api: 0
  search_api_db: 0
  search_api_glossary: 0
  serialization: 0
  shortcut: 0
  simple_block: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  upgrade_status: 0
  user: 0
  views_ajax_history: 0
  views_infinite_scroll: 0
  views_ui: 0
  menu_link_content: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  seven: 0
  claro: 0
  gin: 0
  stable9: 0
  kitchen_karaoke: 0
  karaokedesign: 0
profile: standard
