_core:
  default_config_hash: h0ctmI-lSknN6e9qvO8PKjAPEeopeDR4FnxTYhGcD1k
enabled: true
settings:
  client_id: 854885144183-8cn0mq2547ddkcoefo4cmq50kbi5pdkl.apps.googleusercontent.com
  client_secret: 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
  redirect_url: ''
