name: fourkitchens-karaoke
recipe: pantheon
config:
  framework: drupal8
  site: fourkitchens-karaoke
  id: ab2c6c8d-facb-4664-90fb-582a0d236de2
  xdebug: true
tooling:
  drush:
    service: appserver
    cmd: /app/vendor/bin/drush --root=/app/web
    env:
      DRUSH_OPTIONS_URI: "https://fourkitchens-karaoke.lndo.site"
  drupal:
    service: appserver
    cmd: /app/vendor/bin/drupal
