<?php

/**
 * @file
 * Contains openkj_musixmatch.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function openkj_musixmatch_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the openkj_musixmatch module.
    case 'help.page.openkj_musixmatch':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('MusixMatch API integration with OpenKJ') . '</p>';
      return $output;

    default:
  }
}
