<?php

/**
 * @file
 * Contains fk_karaoke_custom.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function fk_karaoke_custom_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the fk_karaoke_custom module.
    case 'help.page.fk_karaoke_custom':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('General enhancements to the site') . '</p>';
      return $output;

    default:
  }
}

function fk_karaoke_custom_form_openid_connect_login_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if (isset($form['openid_connect_client_google_login'])) {
    $form['openid_connect_client_google_login']['#value'] = t('Log in or Register with Google');
  }
}
